### ISSUE TITLE
Need an icon for "fw-view" inverse or to represent hide. 

### ISSUE THREAD

**Issue by hevayo** [wso2-dev-ux/font-wso2#14]
To show password text in plain text you can use "fw-view" but to hide a password which is in plain text you do not have an appropriate icon. Ideally you would want "fw-view" stricked with a slash "/". 

At-least if we have a "/" icon we can stack to get the desired icon. 

refer [http://fontawesome.io/icon/eye-slash/](http://fontawesome.io/icon/eye-slash/)

**Comment by jeradrutnam** [comment]
Hi Jo,

It's already added to the pack. Will available in the next release. Or you can use the 1.0.3-SNAPSHOT from GitHub for the moment.

Cheers!

[1] https://github.com/wso2-dev-ux/font-wso2/blob/master/icons/hide.svg

**Comment by jeradrutnam** [comment]
Added icon 'slash' and available in the v1.1.0 release.
