### ISSUE TITLE
Icon Request:ESB connector, IS connector and Analytics extensions

### ISSUE THREAD

**Issue by elilmatha** [wso2-dev-ux/font-wso2#28]
Need icons for ESB connector, IS connector, and Analytics extensions for WSO2 store.We need to replace the globe and padlock icon in http://192.168.3.31:9763/store/pages/top-assets

**Comment by jeradrutnam** [comment]
Requested icons are added to the repo: 1fde4d0a1a6ca9d7502a508437602300801674ec
