### ISSUE TITLE
Adding Icons for Analytics dashboard 

### ISSUE THREAD

**Issue by srsharon** [wso2-dev-ux/font-wso2#73]
fw-payload-factory
fw-header
fw-data-mapper
fw-call-mediator
fw-property
fw-log 
fw-in-sequence
fw-out-sequence

**Comment by jeradrutnam** [comment]
whats "fw-header" icon ?

**Comment by srsharon** [comment]
The header icon is to represent the a header of Eg header mediator

**Comment by jeradrutnam** [comment]
Can you share screenshot where this applies?

**Comment by srsharon** [comment]
![image](https://user-images.githubusercontent.com/10986966/27991588-79b500da-6499-11e7-83cb-38e2182e564b.png)

**Comment by srsharon** [comment]
![image](https://user-images.githubusercontent.com/10986966/27991669-1ed9550a-649c-11e7-9df0-7b81e8a887cd.png)
