### ISSUE TITLE
Icon request: fw-continue

### ISSUE THREAD

**Issue by jeradrutnam** [wso2-dev-ux/font-wso2#76]
Need an icon for 'continue' keyword (in a while loop)

![image](https://user-images.githubusercontent.com/7569427/28111831-7c26bc3c-6714-11e7-8769-8949d83de62a.png)

Requested by: Manuranga

**Comment by manuranga** [comment]
note that will be renamed to "next" in the future. @hasithaa https://github.com/ballerinalang/ballerina/issues/2858

**Comment by jeradrutnam** [comment]
Fixed on PR #82
