### ISSUE TITLE
Requesting few missing icons required for Associations in G-REG Publisher

### ISSUE THREAD

**Issue by mushthaq33** [wso2-dev-ux/font-wso2#8]
Please find the icon list below.
1. OwnedBy
2. Security
3. Depends
4. UsedBy

**Comment by srsharon** [comment]
We are working on your request, we will make the icons available soon

**Comment by jeradrutnam** [comment]
Hi,

Above icons are added to the repository. Please download the latest - http://wso2-dev-ux.github.io/font-wso2/

Cheers!
Jerad
