### ISSUE TITLE
Requesting new icons for APIM Life Cycle

### ISSUE THREAD

**Issue by DimalChandrasiri** [wso2-dev-ux/font-wso2#9]
Please create icons for following statuses 

CREATED, 
PROTOTYPED, 
PUBLISHED, 
BLOCKED, 
DEPRECATED, 
RETIRED

**Comment by jeradrutnam** [comment]
Hi Dimal,

Please refer below icons for above request which are already in the repository, will update once others are added to the repository.

CREATED - add (Already in the pack)
PUBLISHED - publish (Already in the pack)
BLOCKED - block (Already in the pack)

PROTOTYPED - (Need to create icon for prototype)
DEPRECATED - (Need to create icon for deprecate)
RETIRED -  (Need to create icon for retire)

Cheers,
Jerad

**Comment by srsharon** [comment]
Hi Dimal, 

The icons have been added to the Icon pack.
